# Gradle
org.gradle.jvmargs=-Xmx3G -Duser.language=en -Duser.country=US
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

# Environment
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.23
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

# Mod
mod_id=flysword
mod_name=Fly Sword Mod
mod_license=GPL-3.0
mod_version=1.2.0
mod_group_id=com.kesar.flysword
mod_authors=Kesar
mod_description=Fly Sword Mod.
